collections_config:
  enTopics:
    name: Topics EN
    path: 'content/en'
    schemas:
      default:
        path: src/_schemas/topic.md
    _enabled_editors:
      - content
      - visual
    output: true
  data:
    path: _data
    schemas:
      doc:
        path: src/_schemas/data/doc.json
        create:
          path: '[relative_base_path]/{slug}.json'

collections_config_override: true

_inputs:
  sidebars:
    type: array
    options:
      structures: _structures.sidebarsGroup
  items:
    type: array
    options:
      structures: _structures.sidebarsItem
  trimTopLeft:
    hidden: true
  trim_top_left:
    hidden: true

_structures:
  sidebarsGroup:
    values:
      - value:
          label:
          items:
  sidebarsItem:
    values:
      - value:
          label:
          url:
          items:

_snippets_imports:
  eleventy_liquid:
    exclude:
      - eleventy_liquid_raw
_snippets:
  eleventy_snippet:
    template: eleventy_liquid_paired_shortcode_positional_args
    inline: false
    preview:
      text: Snippet
      subtext:
        - key: content
    definitions:
      shortcode_name: snippet
      content_key: content
      positional_args:
        - editor_key: snippet_type
          type: string
    _inputs:
      content:
        type: markdown